#!/bin/sh

bspc rule -r "*"

####--- Autostarts ---####
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
# feh --randomize --bg-fill ~/Pictures/backgrounds/dark_pics &
nitrogen --restore &
picom -f &
setxkbmap -layout gb &
dunst &
# killall "nm-applet"
# nm-applet &
# killall "volumeicon"
# volumeicon &
thunar --daemon &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

####--- BSPWM Colours ---####
bspc config normal_border_color "#e0e0eb"
bspc config active_border_color "#666699"
bspc config focused_border_color "#00ff00"
bspc config presel_feedback_color "#bfbfbf"

####--- BSPMW Rules ---####
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a firefox desktop=^1 follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs desktop=^5 state=tiled follow=on
bspc rule -a Shortwave desktop=^9 follow=on
bspc rule -a Thunar desktop=^3 follow=on
bspc rule -a Thunderbird desktop=^7 follow=on state=floating rectangle=1200x1200+20+50
bspc rule -a Abiword desktop=^2 follow=on state=floating rectangle=1200x1200+20+50
